# Generated by Django 5.1.6 on 2025-03-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='Author_name', max_length=50),
        ),
        migrations.AddField(
            model_name='author',
            name='place',
            field=models.CharField(default='Author_place', max_length=50),
        ),
    ]
